### ISSUE TITLE
Problem with scoped packages

### ISSUE THREAD

**Issue by plesiecki** [ds300/patch-package#4] opened 2017-06-22 12:04 UTC
I've got an error while trying to patch scoped npm package, e.g. `@types/rollup`

> Error: Command failed: git add -f 'node_modules/[at]types/rollup'
> fatal: pathspec 'node_modules/[at]types/rollup' did not match any files

**Comment by ds300** [comment] 2017-06-22 15:24
Thanks for the report. I was aware of this problem and the cause but forgot
to make an issue for it. Will try to fix it on sunday or early next week.

**Comment by ds300** [comment] 2017-06-24 14:30
@plesiecki I can't reproduce the error you get. Is that the exact output from the command? In which case, which shell do you use? patch-package can't be replacing `@` with `[at]` as far as I can tell.

**Comment by ds300** [comment] 2017-06-24 14:56
Anyway I fixed the issue that was preventing scoped package support for me at least in 3.1.0. If that works for you, please close the issue. Otherwise any more information you can provide about your environment would be very useful.

**Comment by ds300** [comment] 2017-07-18 14:07
I'm closing this due to inactivity. Feel free to open it again if the issue was not solved :-)

**Closed by ds300** 2017-07-18 14:07 UTC
