### ISSUE TITLE
'No such file or directory' error when applying patch to @types/react-native

### ISSUE THREAD

**Issue by petekp** [ds300/patch-package#82] opened 2018-09-07 15:01 UTC
Hi! 👋  I made some changes to the `@types/react-native` package in a project and got the following error after running `yarn patch-package @types/react-native`:

```
yarn run v1.3.2
$ /Users/petepetrash/code/substrate/node_modules/.bin/patch-package @types/react-native
☑ Creating temporary folder
☑ Building clean node_modules with yarn
☑ Diffing your files with clean files
{ Error: ENOENT: no such file or directory, scandir '/var/folders/w_/h6ysqgj94551ycy8x6zdqbdr0000gn/T/tmp-11743ZEpu6eZGxqko/node_modules/@types/react-native'
    at Object.readdirSync (fs.js:750:3)
    at klawSync (/Users/petepetrash/code/substrate/node_modules/klaw-sync/klaw-sync.js:13:25)
    at Object.exports.makePatch (/Users/petepetrash/code/substrate/node_modules/patch-package/dist/makePatch.js:77:9)
    at /Users/petepetrash/code/substrate/node_modules/patch-package/dist/index.js:24:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/petepetrash/code/substrate/node_modules/patch-package/dist/index.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path:
   '/var/folders/w_/h6ysqgj94551ycy8x6zdqbdr0000gn/T/tmp-11743ZEpu6eZGxqko/node_modules/@types/react-native' }
/Users/petepetrash/code/substrate/node_modules/patch-package/dist/makePatch.js:125
        throw e;
        ^

Error: ENOENT: no such file or directory, scandir '/var/folders/w_/h6ysqgj94551ycy8x6zdqbdr0000gn/T/tmp-11743ZEpu6eZGxqko/node_modules/@types/react-native'
    at Object.readdirSync (fs.js:750:3)
    at klawSync (/Users/petepetrash/code/substrate/node_modules/klaw-sync/klaw-sync.js:13:25)
    at Object.exports.makePatch (/Users/petepetrash/code/substrate/node_modules/patch-package/dist/makePatch.js:77:9)
    at /Users/petepetrash/code/substrate/node_modules/patch-package/dist/index.js:24:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/petepetrash/code/substrate/node_modules/patch-package/dist/index.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This project uses the Yarn workspaces feature, so this may be related to https://github.com/ds300/patch-package/issues/42

**Comment by ds300** [comment] 2019-01-20 22:00
Thanks for the report! :heart: Sorry it took me so long to get around to taking a look.

I completely re-worked the patch creation process for patch-package@6.0.0-12 and can't reproduce this so will close this issue if you don't mind. Please feel free to reopen or open a new issue if you're still having trouble!

**Closed by ds300** 2019-01-20 22:00 UTC

**Comment by petekp** [comment] 2019-01-20 23:39
@ds300 you're awesome - thank you!

**Comment by tbcshifter** [comment] 2019-04-23 15:48
I'm encountering this same error in 6.1.2 running `patch-package react-native`.

```
patch-package 6.1.2
• Creating temporary folder
• Installing react-native@0.57.1 with npm
• Diffing your files with clean files
{ Error: ENOENT: no such file or directory, scandir '/var/folders/pn/__9t3jkx0y99dk28z07wp_pr0000gn/T/tmp-56329nwKmzZ769rP/node_modules/react-native'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.klawSync [as default] (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/node_modules/klaw-sync/klaw-sync.js:13:25)
    at Object.removeIgnoredFiles (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/filterFiles.js:10:24)
    at Object.makePatch (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/makePatch.js:89:23)
    at /Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/index.js:48:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/index.js:47:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/folders/pn/__9t3jkx0y99dk28z07wp_pr0000gn/T/tmp-56329nwKmzZ769rP/node_modules/react-native' }
/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/makePatch.js:150
        throw e;
        ^

Error: ENOENT: no such file or directory, scandir '/var/folders/pn/__9t3jkx0y99dk28z07wp_pr0000gn/T/tmp-56329nwKmzZ769rP/node_modules/react-native'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.klawSync [as default] (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/node_modules/klaw-sync/klaw-sync.js:13:25)
    at Object.removeIgnoredFiles (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/filterFiles.js:10:24)
    at Object.makePatch (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/makePatch.js:89:23)
    at /Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/index.js:48:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/andrew/.nvm/versions/node/v8.11.4/lib/node_modules/patch-package/dist/index.js:47:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)```

**Comment by uzunF** [comment] 2019-11-27 06:47
Hi, If anyone need a solution that trick works for me;
If you use `yarn`, please add end of the line `--use-yarn`
Example;

`yarn patch-package react-native-firebase --use-yarn`
