### ISSUE TITLE
Patch-package tries to apply the same patch twice and fails

### ISSUE THREAD

**Issue by RocketPuppy** [ds300/patch-package#31] opened 2017-11-15 14:47 UTC
I've set patch-package up according to the directions in the README, adding it as a prepare script in my package.json file, and I've added a single patch file. On a clean run with no node_modules, or with the patch not applied yet, the patch works great! However after the patch has been applied running `yarn` again seems to try to apply the patch again which fails. Here's some sample output:
```
[nix-shell:~/project]$ rm -rf node_modules/ && yarn
yarn install v1.0.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "ajv-keywords@2.1.0" has incorrect peer dependency "ajv@>=5.0.0".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.3.2" while you're on "1.0.1".
info To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash
$ patch-package
patch-package: Applying patches...
@types/ramda@0.24.17 ✔
Done in 10.07s.

[nix-shell:~/project]$ yarn
yarn install v1.0.1
[1/4] Resolving packages...
success Already up-to-date.
$ patch-package
patch-package: Applying patches...

**ERROR** Failed to apply patch for package @types/ramda

  This error was caused because Git cannot apply the following patch file:

    patches/@types/ramda+0.24.17.patch

  This is usually caused by inconsistent whitespace in the patch file.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ds300** [comment] 2017-11-15 14:53
Hey, thanks for the report! I can reproduce this. Seems to be an issue with scoped packages only. Will let you know once I've found a fix.

**Comment by RocketPuppy** [comment] 2017-11-15 14:54
Wow, fast response! Thanks!

**Comment by ds300** [comment] 2017-11-15 15:06
I found the issue. It was a dumb mistake of mine. Will push a fix out in the next few minutes.

**Comment by ds300** [comment] 2017-11-15 15:13
![image](https://user-images.githubusercontent.com/1242537/32843333-ccde86b4-ca1f-11e7-9d36-3b125b10f1ab.png)

Fix released in 3.6.1. Thanks again for the report! :heart:

**Closed by ds300** 2017-11-15 15:13 UTC

**Comment by ds300** [comment] 2017-11-15 15:17
@RocketPuppy Did it fix the issue for you? Feel free to reopen if not.

**Comment by RocketPuppy** [comment] 2017-11-15 15:20
@ds300 All fixed! Thanks for the quick patch!
